TacticalPackage.create(title:"Grenadier", description:"Devastator of Zombies", creator:"Chris") 
PrimaryWeapon.create(tactical_package_id:"1", name:"Spas 12", description:"12 gauge madness", image_url:"ahfjf") 
SecondaryWeapon.create(tactical_package_id:"1", name:"Glock", description:"17 rounds of lead in a mag", image_url:"none") 
LethalWeapon.create(tactical_package_id:"1", name:"semtex", description:"plastic explosive", image_url:"none") 
TacticalItem.create(tactical_package_id:"1", name:"Antibiotics", description:"For sickness", image_url:"none")